export const AUTHORIZATION_SUCCESS = "AUTHORIZATION_SUCCESS";
export const AUTHORIZATION_FAIL = "AUTHORIZATION_FAIL";
export const SIGN_OUT = "SIGN_OUT";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
